In [1]:
import torch
import torch.nn as nn

In [29]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

In [30]:
model = Model(n_input_features=6)

In [31]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.1119, -0.2199,  0.1298,  0.3306,  0.0728,  0.2763]],
       requires_grad=True)
Parameter containing:
tensor([-0.0556], requires_grad=True)


In [18]:
FILE = "model.pth"
torch.save(model.state_dict(), FILE)

In [32]:
loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [33]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.1119, -0.2199,  0.1298,  0.3306,  0.0728,  0.2763]],
       requires_grad=True)
Parameter containing:
tensor([-0.0556], requires_grad=True)
